// Generated by tools/build_bible_catalog.py from the official text-only sources.
export const BIBLE_SNAPSHOT = 'v1-f2c898218cdde2ad07b1';
export const BIBLE_MANIFEST_SHA256 = '51448edef30905437e41507635a1234b7249adf1339e1df6aafe83972ea02b9a';
